### ISSUE TITLE
Failed to fetch debian source "tokumx-debs"

### ISSUE THREAD

**Issue by leopoiroux** [Tokutek/mongo#1238]
Hi,
Today I have a 404 on "apt-get update" command.
Do you have problems with your bucket ?
Thanks for your help

`W: Failed to fetch http://s3.amazonaws.com/tokumx-debs/dists/wheezy/main/binary-amd64/Packages  404  Not Found`

**Comment by hrvojem** [comment]
Hi, 

You can now fetch the packages from the Percona repositories:
https://www.percona.com/doc/percona-tokumx/installation_from_packages.html#debian-and-ubuntu

Latest release is TokuMX 2.0.2:
https://www.percona.com/doc/percona-tokumx/release_notes/2.0.2.html

**Comment by leopoiroux** [comment]
It's not only for the "enterprise edition" ?

**Comment by tplavcic** [comment]
It's called enterprise edition because it includes those features but it's now free and open source. So you may use it without problems.

**Comment by leopoiroux** [comment]
Thks
