### ISSUE TITLE
how to check replication lag

### ISSUE THREAD

**Issue by umardraz** [Tokutek/mongo#1246]
Hello

Hello i am using TokuMX v2.0.2-mongodb-2.4.10 as Replica Set

I have 1 Primary and 3 slave, my developers asking me I should tell them about how many seconds behind secondaries from Primary.

How I can check this with TokuMX

Br.

Umar

**Comment by doluiscontreras** [comment]
You can use the following command to get info about your replication:

db.getReplicationInfo()
db.printSlaveReplicationInfo()

You can read more about those commands here : https://www.percona.com/doc/percona-tokumx/replication.html

regards,

Luis

**Comment by umardraz** [comment]
Hello thanks for your reply,

Well both command are useless for me as both are not worked.

Here is the output of  db.printSlaveReplicationInfo()

rebel:PRIMARY>  db.printSlaveReplicationInfo()
source: replica3:27017
        no replication info, yet.  State: SECONDARY
source: replica4:27017
        no replication info, yet.  State: SECONDARY
source: replica6:27027
        no replication info, yet.  State: SECONDARY

and Here is the output of db.getReplicationinfo()

rebel:PRIMARY> db.getReplicationInfo()
Cannot use 'commands' readMode, degrading to 'legacy' mode
{
        "errmsg" : "Could not get stats for local.oplog.rs collection. collstats returned: {\n\t\"ns\" : \"local.oplog.rs\",\n\t\"errmsg\" : \"exception: element is not a number: { scale: undefined }\",\n\t\"code\" : 17015,\n\t\"ok\" : 0\n}"
}

Br.

Umar

**Comment by umardraz** [comment]
Ok Sorry

It worked

Thanks

**Comment by doluiscontreras** [comment]
No problem, you are welcome!
