### ISSUE TITLE
403 Forbidden error trying to install on debian 7

### ISSUE THREAD

**Issue by abrinckm** [Tokutek/mongo#1248]
Following installation instructions, running these commands results in 403:
```
echo "deb [arch=amd64] http://s3.amazonaws.com/tokumx-debs $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/tokumx.list
```

`
apt-get update
`

Results in this error:
`W: Failed to fetch http://s3.amazonaws.com/tokumx-debs/dists/wheezy/main/binary-amd64/Packages  403  Forbidden`

**Comment by george-lorch** [comment]
Tokumx has been end-of-life for almost 2 years now. Please see https://www.percona.com/software/mongo-database/percona-tokumx and https://www.percona.com/blog/2017/04/26/migrate-tokumx-percona-server-mongodb/
