### ISSUE TITLE
With heavy load testing, we "Lock not granted. Try restarting the transaction" for about 30% of our queries

### ISSUE THREAD

**Issue by treeder** [Tokutek/mongo#474]
Under heavy load testing, we get: 

```
exception: nextSafe(): { $err: "Lock not granted. Try restarting the transaction.", code: 16759 }
```

For about 30% of our requests, which makes it pretty unusable.

Using tokumx 1.1.1

**Comment by bitliner** [comment]
I have some problem. 
I am actually getting this error because of a lot updates without the right index.
It looks like each update requires too much time, so the queue of operations increases, and a lock related timeout is fired, and the operations on the queue are dropped out.

After having setted the index up, the error does not appear anymore.

**Comment by bitliner** [comment]
@leifwalsh is there any update on this issue?

I still continue receiving the same error, that blocks the process. 

Apart of adding indexes in case the query/insert/update is too much time consuming, is there any other way to handle this issue?

**Comment by randomComitter** [comment]
@leifwalsh we're using Toku v2.0.1 and we also have the same issue. 
In our case we have several processes that might at the same time execute query like:

```
// date is set automatically, typos expected here, the real query is generated
db.getCollection('collectionName').findAndModify({
    query: { 
        $or: [
            {"lockedAt": {$exists: false}},
            {"lockedAt": {$lt: new ISODate('2016-08-26 16:46:53.515Z')}},
        ]
    }, 
    update: {$set: { "lockedAt": new ISODate()} },
    new: true
})
```

There is a [Percona article](https://www.percona.com/blog/2013/09/18/lock-diagnostics-and-index-usage-statistics-in-tokumx-v1-2-1/) about _lock not granted_ error, but unfortunately it just gives hints on how to find conflicting operation but doesn't give suggestions on how to fix it.

Is this expected to be fixed, or are the ways to mitigate this error?
